### ISSUE TITLE
@Gautam & @Marco: Jumbotron picture options

### ISSUE THREAD

**Issue by ahmadelgamal** [gtankha/bootcamptravel#9]
![AdobeStock_50172353_Preview](https://user-images.githubusercontent.com/23747147/92301350-0e83e580-ef18-11ea-8072-8bbbc49e5e9d.jpeg)
![AdobeStock_257330669_Preview](https://user-images.githubusercontent.com/23747147/92301352-104da900-ef18-11ea-8464-40b7041842f9.jpeg)
![AdobeStock_257944804_Preview](https://user-images.githubusercontent.com/23747147/92301353-10e63f80-ef18-11ea-8ce6-d41ce581387b.jpeg)
![AdobeStock_278321575_Preview](https://user-images.githubusercontent.com/23747147/92301355-117ed600-ef18-11ea-94cc-0b2a7310d534.jpeg)
![AdobeStock_300756454_Preview](https://user-images.githubusercontent.com/23747147/92301357-12176c80-ef18-11ea-9f71-fa1d49b69552.jpeg)

**Comment by ahmadelgamal** [comment]
Let me know if you like one of these and I will buy it, God willing.

**Comment by marcobjj** [comment]
I like number 2 and 3 from top down
